POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlZXIxd2UiLCJpZCI6IjYwNDNmN2RkNTJkOThiMWNjN2U5ZTRkMiIsImlhdCI6MTYxNTIzODUwOH0.e37QTyVsgLN3rNuWbwFFFmh4jYOHhgaRZNR71TxvWiE

{
  "title": "testtest",
  "author": "Sergii Kirianov",
  "url": "resrw",
  "likes": 10,
  "userId": "6043f7dd52d98b1cc7e9e4d2"
}